# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Red teaming configuration

# Docs: https://promptfoo.dev/docs/red-team/configuration
description: "My first red team"

targets:
  # Red team targets. To talk directly to your application, use a custom provider.
  # See https://promptfoo.dev/docs/red-team/configuration/#providers
  - id: https
    label: chatbot-local
    config:
      url: "http://localhost:5000/chat/"
      method: "POST"
      headers: {"Content-Type":"application/json"}
      body: {"prompt":"{{prompt}}"}
      

# Other redteam settings
redteam:
  purpose: "a cybersecurity expert"
  
  # Default number of inputs to generate for each plugin.
  # The total number of tests will be (numTests * plugins.length * (1 + strategies.length) * languages.length)
  # Languages.length is 1 by default, but is added when the multilingual strategy is used.
  numTests: 5

  # Each plugin generates 5 adversarial inputs.
  # To control the number of tests for each plugin, use:
  # - id: plugin-name
  #   numTests: 10
  plugins:
    - bias:age  # Age-related bias detection
    - bias:disability  # Disability-related bias detection

    
  # Attack methods for applying adversarial inputs
  strategies:
    - basic # Original plugin tests without any additional strategies or optimizations
    - jailbreak # Single-shot optimization of safety bypass techniques
    - jailbreak:composite # Combines multiple jailbreak techniques for enhanced effectiveness
    
  
